### ISSUE TITLE
数据集格式

### ISSUE THREAD

**Issue by simplew2011** [spytensor/pytorch_img_classification_for_competition#10]
请问dataset参数数据集文件格式是怎样的

**Comment by Lotus-Blue** [comment]
我也想问，这个没有真的是很烦

**Comment by anyun-hy** [comment]
数据集格式没有，就是没办法啊

**Comment by spytensor** [comment]
不至于代码都看不懂。

**Comment by anyun-hy** [comment]
你说的都对，我们好像在说格式问题吧，你这回复。。。。。
扯代码来了








------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月6日(星期二) 晚上7:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [spytensor/pytorch_img_classification_for_competition] 数据集格式 (#10)





 
不至于代码都看不懂。
 
&mdash;

**Comment by anyun-hy** [comment]
都是神人啊，回复雷人




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月6日(星期二) 晚上7:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [spytensor/pytorch_img_classification_for_competition] 数据集格式 (#10)





 
不至于代码都看不懂。
 
&mdash;

**Comment by spytensor** [comment]
@guxinghaoyun https://github.com/spytensor/pytorch_img_classification_for_competition/blob/75cdbf998216558417e63b33c5685309b24209df/utils/misc.py#L108

**Comment by anyun-hy** [comment]
你是想提示我在这修改吗？我看不到你给我发的信息，都是邮件转发的




首先，我很感谢你的指导，我这没问题，自己能够修改，要是你本人是原作者，那我想给你提一个bug，是pytorch 版本更新以后存在的bug ,你可以考虑要不要修改一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月8日(星期四) 下午4:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [spytensor/pytorch_img_classification_for_competition] 数据集格式 (#10)





 
@guxinghaoyun https://github.com/spytensor/pytorch_img_classification_for_competition/blob/75cdbf998216558417e63b33c5685309b24209df/utils/misc.py#L108

**Comment by spytensor** [comment]
@guxinghaoyun 非常抱歉，不太可能针对后续的pytorch版本进行维护更新；本项目的本意是为那些经常做视觉分类比赛的人提供便利的，并不提供给初学者，其次这里是说明，通过这个代码就可以看出数据格式：

```python
- train\
   0\img1.png
   0\img2.png
   1\img1.png
   1\img2.png
```

0,1,代表类别，int(file.split(os.sep)[-2])

**Comment by anyun-hy** [comment]
谢谢，我是那天自己想写一个经常使用的框架，所以就看了看您的代码。写的很完美，我给你提交一下bug 吧，毕竟使用你的代码就一句话的使用方法发生了变化

现在使用reshape()&nbsp;


建议能将你刚才发给我的这个样例，加入进readme.md文件


才疏学浅，暂时没有遇到别的，使用过程中，出现别的bug我会记录下来发给你






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月8日(星期四) 下午4:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [spytensor/pytorch_img_classification_for_competition] 数据集格式 (#10)





 
@guxinghaoyun 非常抱歉，不太可能针对后续的pytorch版本进行维护更新；本项目的本意是为那些经常做视觉分类比赛的人提供便利的，并不提供给初学者，其次这里是说明，通过这个代码就可以看出数据格式：
 - train\    0\img1.png    0\img2.png    1\img1.png    1\img2.png
 
0,1,代表类别，int(file.split(os.sep)[-2])
 
&mdash;

**Comment by anyun-hy** [comment]
还是很感谢你尽然能回复我信息，我就是随手写上去的，问题都好解决，调试一下就没问题了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "spytensor/pytorch_img_classification_for_competition"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月8日(星期四) 下午4:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [spytensor/pytorch_img_classification_for_competition] 数据集格式 (#10)





 
@guxinghaoyun 非常抱歉，不太可能针对后续的pytorch版本进行维护更新；本项目的本意是为那些经常做视觉分类比赛的人提供便利的，并不提供给初学者，其次这里是说明，通过这个代码就可以看出数据格式：
 - train\    0\img1.png    0\img2.png    1\img1.png    1\img2.png
 
0,1,代表类别，int(file.split(os.sep)[-2])
