### ISSUE TITLE
训练时候出现gradient overflow并且loss为NAN，梯度爆炸

### ISSUE THREAD

**Issue by Haitons** [spytensor/pytorch_img_classification_for_competition#3]
您好，我现在用您的代码在我的数据上进行图片分类。在训练时有时候会出现gradient overflow，请问这是什么原因？还有很容易loss就变为NAN，导致训练崩溃，可以指点一下是哪里出现问题了吗，感谢！

**Comment by spytensor** [comment]
看看lr是不是设置过大
