### ISSUE TITLE
加载checkpoints中一点小问题

### ISSUE THREAD

**Issue by WTianzhu** [spytensor/pytorch_img_classification_for_competition#4]
main.py中142行 `model.**module.**load_state_dict(checkpoint['state_dict'])->>model.load_state_dict(checkpoint['state_dict'])`

**Comment by spytensor** [comment]
@WTianzhu 多谢指出错误！

**Comment by 1299372364** [comment]
main.py中142行 model.module.load_state_dict(checkpoint['state_dict'])
>> model.load_state_dict(checkpoint['state_dict'])
