### ISSUE TITLE
将resnet101更改为vgg16模型后，运行出错

### ISSUE THREAD

**Issue by Leo-cloud** [spytensor/pytorch_img_classification_for_competition#5]
使用了自己的数据集，大小为224X224，在config.py中将resnet101改为了vgg16，运行后报错。

![2020-09-01 09-24-23屏幕截图](https://user-images.githubusercontent.com/54903022/91784241-fae53000-ec34-11ea-84e7-0fb2e140650b.png)
![2020-09-01 09-14-38屏幕截图](https://user-images.githubusercontent.com/54903022/91784249-ff114d80-ec34-11ea-89a4-62728e19e641.png)

**Comment by spytensor** [comment]
VGG16需要单独修改最后的fc层 @Leo-cloud

**Comment by Leo-cloud** [comment]
> VGG16需要单独修改最后的fc层 @Leo-cloud
这个报错不是输入层的原因吗，m1: [32 x 512]表示的应该是[batch size x in features]吧，可是在配置文件以及数据图像的大小均为224x224
