### ISSUE TITLE
关于测试集的问题

### ISSUE THREAD

**Issue by Leo-cloud** [spytensor/pytorch_img_classification_for_competition#7]
在执行 main.py 进行训练的过程中，没有涉及到测试集的加载和使用，https://github.com/spytensor/pytorch-image-classification#pytorch-image-classification 在您之前的这个代码里面是有这部分内容的，这是为什么呢?
在使用 test.py 预测的时候，出现以下报错：
![2020-09-03 15-04-02屏幕截图](https://user-images.githubusercontent.com/54903022/92082262-de90f100-edf6-11ea-839d-67aa1a9833c4.png)

**Comment by spytensor** [comment]
老哥，建议你学一下python再搞比赛，，，，， @Leo-cloud

**Comment by Leo-cloud** [comment]
> 老哥，建议你学一下python再搞比赛，，，，， @Leo-cloud

打扰到你，十分抱歉呀。我不是要参加比赛，是刚开始学习，想从一个图像分类的实例来学习，网上搜索看到你的帖子挺详细的，所以来学习，占用到你的时间，不好意思，可否指导一下我的疑惑，可以付费咨询吗？
